name: "Syntax Check - Python"

on:
  workflow_call:

jobs:
  pylint_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 # This action sets up Python

      - name: Install Dependencies
        run: pip install pylint # Install your Python dependencies

      - name: Lint Check
        run: pylint lambdas/ --disable import-error

  format_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 # This action sets up Python

      - name: Install Dependencies
        run: pip install black # Install your Python dependencies

      - name: Format Check
        run: black --check lambdas/
  
  terraform-lint:
    name: Lint and Format Terraform Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Format Terraform files
        run: terraform fmt -check -recursive